### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [Altech/todoist-clone#3]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by Altech** [comment]
@codehangen What kind of trouble is this?

This will be a project I created for learning Firebase and React. I can answer small questions, but major changes may be difficult.

**Comment by ghost** [comment]
Hi Altech.

> @codehangen What kind of trouble is this?

I'm helping the todo-txt repository, which is a task specification, I'm thinking of creating a mobile/desktop version based on your code that reads the todo-txt file and renders it as todoist

> This will be a project I created for learning Firebase and React. I can answer small questions, but major changes may be difficult.

thank you for feedback.
